### ISSUE TITLE
For release

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nlmixr2est#10]
- [x] foce works
- [x] foi works
- [x] fo works
- [x] posthoc works
- [x] focei works
- [x] focei works without etas
- [x] saem works
- [x] saem likelihood methods
- [x] saem standard error works
- [x] saem doesn't always add cwres
- [x] when cwres is added shows focei instead of focei likelihood
- [x] saem returns nlmixr style object
- [x] saem fix omega check
- [x] nlme works
- [x] bootstrapFit works
- [x] bootplot works
- [x] npde works
- [x]  tidy works
- [x] Cache focei setup
- [x] covarSearchAuto
- [x] preconditionFit
- [x] piping
- [ ] saem warns on bounded variables

**Comment by mattfidler** [comment]
Tests:
- [ ] Fix theta
- [ ] Fix Omega
- [ ] Fix Sigma
- [ ] Bounds
- [ ] Calc likelihood types
- [ ] Time varying covariates saem
- [ ] npde calculation on each item

**Comment by billdenney** [comment]
* Build pkgdown website?

**Comment by mattfidler** [comment]
Agreed, it is part of the automated build scripts.  I hope all are successful.

**Comment by mattfidler** [comment]
Remove or update nlmixrPred
