### ISSUE TITLE
Should nlmixr2est Depend on rxode2?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#100]
I think that it would be preferable to have nlmixr2est Depend on rxode2 instead of just importing it.  Does that make sense to you?

https://github.com/nlmixr2/nlmixr2est/blob/d26ef5c7218f72ee5225209cb901b6f54b2aa88e/DESCRIPTION#L4-L8

Related to that, should `nlmixr2` Depend on nlmixr2est and rxode2?

**Comment by mattfidler** [comment]
It makes certain things easier, though I personally steer away from this approach in general. 

The only reason why I did this with `nlmixr2data` is because I cannot re-export datasets for whatever reason.

**Comment by mattfidler** [comment]
Perhaps we can ask others.

As a note the `tidyverse` package simply re-exports packages; you can see in their `DESCRIPTION` file:

https://github.com/tidyverse/tidyverse/blob/main/DESCRIPTION

**Comment by billdenney** [comment]
I agree that it's a good thing to ask others.

In the end, tidyverse attaches the packages, but they do it in a more convoluted way than other packages do: https://github.com/tidyverse/tidyverse/blob/main/R/attach.R .  There is probably a reason for the complexity, but as seen in the comments in that file, there are some issues that have cropped up with the way they do it.

The reason I was suggesting adding these to the `Depends` section is because it would help to have access to the full stack of tools when loading `nlmixr2`.  As a user, I'd not want to have to think if I loaded `nlmixr2est` or `rxode2`, and as a developer, I'd not want to have to remember to manually reexport the functions I wanted to expose up in `nlmixr2` from the underlying packages.

**Comment by mattfidler** [comment]
From my point of view, the only user facing functions are basically `nlmixr`, `rxode`, `et`, `rxSolve`, `rxControl`, `foceiControl`, `saemControl`, `nlmeControl`, `eventTable`, `model`, `ini`, and now `rxAppendModel` everything else is really for developers.

**Comment by mattfidler** [comment]
I prefer using the `rxode2::` notation if I need to access a function from `rxode2`

**Comment by billdenney** [comment]
That makes sense to keep the interface simple with carefully-considered user-facing functions.
