### ISSUE TITLE
R CMD Check note about envir

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#105]
There is an undefined variable in nlmixr2Est0: https://github.com/nlmixr2/nlmixr2est/runs/5605797613?check_suite_focus=true#step:19:231

(PR coming momentarily)

**Comment by billdenney** [comment]
Two more notes:
https://github.com/nlmixr2/nlmixr2est/runs/5611799035?check_suite_focus=true#step:19:65

https://github.com/nlmixr2/nlmixr2est/runs/5611799035?check_suite_focus=true#step:19:71

**Comment by mattfidler** [comment]
These notes are new, I saw them in `dparser` to
