### ISSUE TITLE
Crash in focei_wang testing

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#119]
https://github.com/billdenney/nlmixr2CRANtesting/blob/629579886a9d117299f0b228237cba38a9b3c67e/outputs/nlmixr2est_test.txt#L1825-L1886

I'm about to run gdb.

**Comment by billdenney** [comment]
It didn't replicate with running just the focei_wang tests (`testthat::test_file()`) under gdb, but #120 happened.  Trying again with `devtools::test()`.

**Comment by billdenney** [comment]
And, it didn't replicate under gdb with a first pass through focei-wang.

**Comment by mattfidler** [comment]
This is the fun of C code sometimes...  It is a bug, but I am unsure where it lives. 

I will close it for now.
