### ISSUE TITLE
Unused Code?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#163]
While looking through the code for the M4 code review, I saw these lines that looked out of place.  I did a quick grep for NETAs, NTHETAs, and NSUBs in the code base, and I didn't see them anywhere else.  I think that they can be removed.

https://github.com/nlmixr2/nlmixr2est/blob/145673a74d31219889a6e77fa84feaefa22cb3c4/src/inner.cpp#L18-L20

**Comment by mattfidler** [comment]
Can probably remove
