### ISSUE TITLE
Warning message indicating possible problems in optimization should be shown on model summary

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#198]
I'm running a problem near the edge of its information.  With that, I am getting a warning at the end of running the model saying "last objective function was not at minimum, possible problems in optimization".

I think that should be printed with the model summary in this section:

```
  Covariance Type ($covMethod): s
  No correlations in between subject variability (BSV) matrix
  Full BSV covariance ($omega) or correlation ($omegaR; diagonals=SDs) 
  Distribution stats (mean/skewness/kurtosis/p-value) available in $shrink 
  Minimization message ($message):  
    Normal exit from bobyqa 
```

I think that it makes sense in the "Minimization message" section, but somewhere else may make more sense.

**Comment by billdenney** [comment]
Also, is there a typical way to fix the fact that the last OFV is not at the minimum?

**Comment by mattfidler** [comment]
The `$message` comes from whatever optimizer you use, I would say they should probably remain separate, though I get your point.  It becomes more difficult to see where things come from if you separate them.

In theory you can use whatever optimizer you want for the outer problem.

**Comment by mattfidler** [comment]
> Also, is there a typical way to fix the fact that the last OFV is not at the minimum?

No.  I try a different estimation method to see if it performs better, but it could be because:

- Lag time/ estimated duration/effects etc where you estimate a step size.  This is reset at the very end of the problem 
- The fact that each problem is an initial value problem.  So, by providing the last set of etas you may actually get to a better solution then repeating the "best" solution.  This implies the surface is a bit flat and or odd, but I'm unsure if you can fix this issue.

**Comment by billdenney** [comment]
FYI, I'm getting the warning about non-minimum OFV on all the models I'm running now.  (That may be a separate issue than the original one.)

``` r
library(nlmixr2)
#> Loading required package: nlmixr2data
pheno <- function() {
  ini({
    tcl <- log(0.008) # typical value of clearance
    tv <-  log(0.6)   # typical value of volume
    ## var(eta.cl)
    eta.cl + eta.v ~ c(1, 
                       0.01, 1) ## cov(eta.cl, eta.v), var(eta.v)
    # interindividual variability on clearance and volume
    add.err <- 0.1    # residual variability
  })
  model({
    cl <- exp(tcl + eta.cl) # individual value of clearance
    v <- exp(tv + eta.v)    # individual value of volume
    ke <- cl / v            # elimination rate constant
    d/dt(A1) = - ke * A1    # model differential equation
    cp = A1 / v             # concentration in plasma
    cp ~ add(add.err)       # define error model
  })
}

fit <- nlmixr(pheno, pheno_sd, "focei",
              control=list(print=0))
#> ℹ parameter labels from comments will be replaced by 'label()'
#> rxode2 2.0.7 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
#> calculating covariance matrix
#> done
#> → Calculating residuals/tables
#> ✔ done
#> → compress origData in nlmixr2 object, save 33192
#> → compress parHist in nlmixr2 object, save 2960
#> Warning: gradient problems with initial estimate and covariance; see $scaleInfo
#> Warning: last objective function was not at minimum, possible problems in
#> optimization
#> Warning: ETAs were reset to zero during optimization; (Can control by
#> foceiControl(resetEtaP=.))
#> Warning: initial ETAs were nudged; (can control by foceiControl(etaNudge=.,
#> etaNudge2=))
```

<sup>Created on 2022-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mattfidler** [comment]
I think that this can be closed since I doubt that I will move general observations from `nlmixr2` to optimizer specific messages stored  in `$message`.  However, documentation of the difference would be probably the right approach here.

**Comment by mattfidler** [comment]
Change the `runInfo` to print out using `cli::cli_li()`
