### ISSUE TITLE
Warning about non-minimum OFV on all the models I'm running now. 

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nlmixr2est#202]
FYI, I'm getting the warning about non-minimum OFV on all the models I'm running now.  (That may be a separate issue than the original one.)

``` r
library(nlmixr2)
#> Loading required package: nlmixr2data
pheno <- function() {
  ini({
    tcl <- log(0.008) # typical value of clearance
    tv <-  log(0.6)   # typical value of volume
    ## var(eta.cl)
    eta.cl + eta.v ~ c(1, 
                       0.01, 1) ## cov(eta.cl, eta.v), var(eta.v)
    # interindividual variability on clearance and volume
    add.err <- 0.1    # residual variability
  })
  model({
    cl <- exp(tcl + eta.cl) # individual value of clearance
    v <- exp(tv + eta.v)    # individual value of volume
    ke <- cl / v            # elimination rate constant
    d/dt(A1) = - ke * A1    # model differential equation
    cp = A1 / v             # concentration in plasma
    cp ~ add(add.err)       # define error model
  })
}

fit <- nlmixr(pheno, pheno_sd, "focei",
              control=list(print=0))
#> ℹ parameter labels from comments will be replaced by 'label()'
#> rxode2 2.0.7 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
#> calculating covariance matrix
#> done
#> → Calculating residuals/tables
#> ✔ done
#> → compress origData in nlmixr2 object, save 33192
#> → compress parHist in nlmixr2 object, save 2960
#> Warning: gradient problems with initial estimate and covariance; see $scaleInfo
#> Warning: last objective function was not at minimum, possible problems in
#> optimization
#> Warning: ETAs were reset to zero during optimization; (Can control by
#> foceiControl(resetEtaP=.))
#> Warning: initial ETAs were nudged; (can control by foceiControl(etaNudge=.,
#> etaNudge2=))
```

<sup>Created on 2022-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

_Originally posted by @billdenney in https://github.com/nlmixr2/nlmixr2est/issues/198#issuecomment-1233392542_

**Comment by mattfidler** [comment]
Probably because of the way the reset occurred as introduced by generalized log-likelihood

**Comment by mattfidler** [comment]
@billdenney This was true in the last release.  Can you provide a problem where this was not true in the last release but true in this release.  Otherwise I will close it for now.

**Comment by billdenney** [comment]
It does seem to affect both the previous and current releases.

**Comment by mattfidler** [comment]
Which means it does not have to do with the reset.  

It is an initial value problem.  Since it recycles the `eta` initial estimates with each iteration it could have a "better" solution  during the ETA optimization. 

In the case of `pheno` the difference is very small

**Comment by mattfidler** [comment]
I think this has been true for `pheno` for awhile.  I just checked `nlmixr` (instead of `nlmixr2`) and it was the same.
