### ISSUE TITLE
Need to allow table step to be more robust

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nlmixr2est#254]
https://github.com/nlmixr2/nlmixr2est/blob/f948885be24d3efbf72bec13bee0a84c19a6d39e/R/resid.R#L81-L126

**Comment by mattfidler** [comment]
` rxode2::atolRtolFactor_(op_focei.odeRecalcFactor);`

**Comment by mattfidler** [comment]
https://github.com/nlmixr2/rxode2/blob/47b2e7739debf8a1b5b7f893c603cd6ac64f1f3b/src/rxData.cpp#L1453-L1462

**Comment by billdenney** [comment]
@mattfidler , Is there documentation of what `fit$methodOde` is?  Specifically, when running the code now I see that it is `2`, but I don't know which method that is.  The choices appear to be `c("liblsoda", "lsoda", "dop853", "indLin")` (from `?rxode2::rxSolve`), but I don't know which is `2`.

**Comment by mattfidler** [comment]
Ah.  I was about to post a table with the link

**Comment by mattfidler** [comment]
The `$methodOde` still works, but it actually resides in `$rxControl$method`.  I guess I made `$methodOde` point to the new location.

**Comment by mattfidler** [comment]
In general `indLin` is not ready for prime time, so no it shouldn't be cycled through.  

I also think that if you are using `lsoda` you really  should only use `liblsoda` for the recycling.
