### ISSUE TITLE
Does this line of code do anything?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#266]
This line doesn't seem to do anything.  Am I missing something or can it be removed?

https://github.com/nlmixr2/nlmixr2est/blob/74dd7236fc6d29f3ff591f82a3ae79667ae98956/R/nlmixr2Est.R#L40

**Comment by mattfidler** [comment]
Probably can be removed

**Comment by billdenney** [comment]
The end answer is that it does something...  (TBD later what exactly that something is.)
