### ISSUE TITLE
Fuzzy text in print header for FOCEi

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#270]
When I was looking at model output in RStudio just now, the heading line indicating the type of estimation was fuzzy:

![image](https://user-images.githubusercontent.com/10359931/198238155-de9a3127-9bda-403b-85ff-3a283189ec6f.png)

I assume that this is a `crayon`-related issue.  (Or, maybe it was intentional because it's an "approximation" 😄 .)

**Comment by mattfidler** [comment]
Or maybe it is `RStudio`

Emacs:

![image](https://user-images.githubusercontent.com/514778/198483990-a672d148-b138-4b16-b714-fb033b5bfa92.png)

Terminal:

![image](https://user-images.githubusercontent.com/514778/198485281-a6d7b0e1-7ef5-4dcd-84e2-db6a8632af54.png)

Rstudio:

![image](https://user-images.githubusercontent.com/514778/198486445-6c25c9de-d8b0-443a-9d49-6563e90230dd.png)

**Comment by billdenney** [comment]
There is code that calls it "blurred":

https://github.com/nlmixr2/nlmixr2est/blob/7237ac1c54a176e766b9290e70b4d23b3acef2af/R/saem.R#L673

Perhaps it should use `cat(crayon::italic$silver("foo"))` instead?

**Comment by mattfidler** [comment]
That is fine if you wish to change it.

**Comment by mattfidler** [comment]
I will change it @billdenney

**Comment by billdenney** [comment]
Ha!  I love the PR name.
