### ISSUE TITLE
Speed up testing

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#293]
I have been working in some of the various testing scripts that we have across the `nlmixr2`-verse in the past few days.  I wonder if we can speed up testing by doing all the model estimation required for the tests once and then reusing those estimates through all the tests that need them.

I'd have to do some investigation to figure out the best way to do a "run once, use many times" in testthat.  They have deprecated the setup functions and similar, so it will take some trying, I think.  The goals I'd have are that the tests would work independently (you only need to run the current `testthat/test-*.R` script) and also they would work faster when run sequentially.  I think it would be some form of caching function, but I don't immediately know what that would look like.

My first thought is to use the `memoise` package to cache model estimation results and then make sure that we have a few, consistent tests that are used throughout.

Thoughts?

**Comment by billdenney** [comment]
As I've thought about it a bit more, an important consideration (that may make `memoise` not work) is that you would want the tests to fully rerun when a new testing session starts.  `memoise` would likely cause issues there as the tests may not rerun when restarted in the same session.  I don't want this to make things too complicated, either.

**Comment by mattfidler** [comment]
I'm not sure what the best solution is, maybe saving the fit in the directory and then loading it in.  Then have a tear-down script that will remove it.  But with parallel running it makes it even more complicated.

**Comment by mattfidler** [comment]
I agree this would be nice, but since there hasn't been any movement on this for awhile,  I will close this
