### ISSUE TITLE
How to track down "NAs introduced by coercion"

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#295]
I just fit a model where a warning of `NAs introduced by coercion` was noted.  That should not have happened with the model, so I'd like to track it down, but I don't know where the data modification causing it would have occurred.

Can you give any pointers to help track down that warning?  (I don't know if it is an `nlmixr2est` or `rxode2` issue, since it occurred during a model estimation call, I am starting here.)

**Comment by billdenney** [comment]
In case it helps, the issue occurred with `saem` estimation, and there was a note saying "Error : Error calculating covariance via linearization" at the end of the estimation.  It did not happen with `focei` estimation.

**Comment by billdenney** [comment]
The warning was captured somewhere else, so I couldn't find it that way.  After working at it a bit more, I found that I was getting the following warning:

```
Ri <- backsolve(qr.R(qr(X)), diag(npar))
# Error in qr.default(X) : NA/NaN/Inf in foreign function call (arg 1)
```

here:

https://github.com/nlmixr2/nlmixr2est/blob/770adad0071797dc3183eafff1b5ace89fb83eaf/R/saem_fit_aux.R#L358

It appears that the `Xi` list is made up of one element per subject and one row within the element per observation.  (That's mostly a guess.)  All of my `Xi` elements end in `NaN`, and I think that may be related to all the final measurements for subjects being BLQ.  Is my guess about what makes `Xi` correct?  Might there be an issue related to the calculation with M3-method estimation?

(I'm not sure if this is the same issue that I started with, but it seems to possibly be an issue.)

**Comment by mattfidler** [comment]
Without a reprex, I'm afraid that I can't do much.  Since this is 2 years old, I am closing this.
