### ISSUE TITLE
Should "here!!!" print during the covariance step?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#298]
I just saw `here!!!` during the covariance step of an focei estimation.  My guess is that this line should be removed, but maybe there is a reason for it.

https://github.com/nlmixr2/nlmixr2est/blob/770adad0071797dc3183eafff1b5ace89fb83eaf/src/inner.cpp#L5614

**Comment by mattfidler** [comment]
It was a drbugging statement I didnt take our.
