### ISSUE TITLE
Get the confidence intervals from the defined uncertainty method

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#305]
For alternate covariance types, use the most relevant way to capture the CI rather than multivariate normal (e.g. use quantiles with bootstrap).

**Comment by mattfidler** [comment]
There is currently no alternative covariance types for the standard error calculation.  The covariance is always based on the multivariate normal.  The ETAs also have to follow a multivariate normal, so their covariance are multivariate normal.

I don't know what you mean here, nor do I know how to implement what you are asking a priori.

**Comment by mattfidler** [comment]
For now, I will simply close this until I understand a use case and think it is worthwhile to add.
