### ISSUE TITLE
Documentation Request: How can I use alternate distributions?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#331]
I was wanting to perform an estimation using a t-distribution, but I don't see to incorporate it.

Specifically, I'd like to do something like an additive plus proportional standard deviation with a t-distribution degrees of freedom fit.

Am I missing the docs or if not, can you give a quick example of how to use it?

**Comment by mattfidler** [comment]
There is some documentation now in rxode2
