### ISSUE TITLE
Add simulation method, ie  `est="simulation"`, "

### ISSUE THREAD

**Issue by snailittle** [nlmixr2/nlmixr2est#332]
mod_sim <- nlmixr(object=fit_saem_rev, data=simData, est="simulation")
ℹ use `control` from prior fit
Error: do not know how to validate control for `est="simulation"`, please add `getValidNlmixrCtl.simulation` method

**Comment by mattfidler** [comment]
Moved to `nlmixr2est` and changed it into a feature request.
