### ISSUE TITLE
saem estimation not occurring in parallel

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#343]
I have a moderately long model estimation with saem that is not running in parallel.  I'm running it in `targets` which I don't think is causing the 

One saem step takes about 10-20 seconds, and when I look at `top` from the Linux console, the R process is only using 1 CPU.  At the beginning of the estimation, it seems to detect the number of threads correctly:

```
params: [[omitted list of parameter names]]
rxode2 2.0.13.9000 using 16 threads (see ?getRxThreads)
  no cache: create with `rxCreateCache()`
```

Is there something that must be done to make saem estimation occur in parallel?

**Comment by mattfidler** [comment]
Try the following before running:
```
rxode2::setRxThreads(percent=100, throttle=1)
```

My guess is you have a small number of subject IDs

**Comment by billdenney** [comment]
It's still using a single thread.  There are 122 subjects in the dataset.

**Comment by mattfidler** [comment]
Sorry to say that I don't know why.  I checked on my computer with the `warfarin` example and it does run multiple threads

**Comment by mattfidler** [comment]
Wait, 

modeled rates, infusions, durations, lag-time and bioavailabilities cannot be run in parallel currently.  It corrupted the solve.

**Comment by mattfidler** [comment]
This is known and not about saem, and something I am aware of but haven't fixed yet.  You can open an issue in `rxode2` if you want.  I have tried to fix it a couple of times but haven't managed it yet.

**Comment by billdenney** [comment]
Aha! Bioavailability is the issue for my model.
