### ISSUE TITLE
Suggestion: Deprecate `nlmixr2NlmeControl()`

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#344]
The function name for `nlmixr2NlmeControl()` that is consistent with the rest of nlmixr2 is `nlmeControl()`.  Should we switch to using that name and deprecate `nlmixr2NlmeControl()`?

**Comment by mattfidler** [comment]
I didn't only because `nlme` has `nlme::nlmeControl()`.  Maybe others can weigh in....

It is simply a list that is validated, I'm ok with having both.  This is the same reason there is a `rename()` and `rxRename()` function.

**Comment by billdenney** [comment]
This is low priority; I was going through the code for a different reason, and I thought that this may have been residual from prior work.
