### ISSUE TITLE
`$parFixed` shows incorrect BSV

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#366]
I have a model where I mix log-scale and linear scale IIV for different parameters.  The BSV column of $parFixed shows 1.00 even though the real CV is ~300%.

The issue is probably in this code:

https://github.com/nlmixr2/nlmixr2est/blob/42589c538c722086fdd2d839f7230e2be10cf641/R/nlmixr2output.R#L131-L184

**Comment by mattfidler** [comment]
Without a reproducible example, this is of course something that I cannot look at.

However, note that it doesn't always show `BSV%` depending on your model it may be a `SD`.  For example `logit`/`expit` will show `SD` instead of `BSV%`  It even changes the column name.

Double check that this isn't expected behavior.  

If it is miss-classifying the value, then the error is probably not in the code you listed.

**Comment by billdenney** [comment]
I understood that I didn't give you much to work with here.  The value for the BSV component in the $iniDf is about 250 while the comparable value for the theta that goes with it is about 40.  The values have no transformation -- just simple addition.

Since they are added together, I initially thought that it would give a CV of about 600%.  If it were a SD, I expected to see 250.  The column header suggests that one of the BSV values is a CV and the other is an SD.

Once I understand what is happening for my problem better, hopefully I can make a reprex.

**Comment by mattfidler** [comment]
Thats not how its calculated

**Comment by billdenney** [comment]
In that case, it's not clear to me what is being represented in that column when the value is not the log-scale standard deviation transformed to the percent CV scale.

**Comment by mattfidler** [comment]
That is it does not use `theta` in the calculation.

For the SD calculations it uses `sd(omegaDiagonal))`

For the CV% it uses the exact lognormal formula:

`v = sqrt(exp(v) - 1) * 100))`


https://github.com/nlmixr2/nlmixr2est/blob/42589c538c722086fdd2d839f7230e2be10cf641/R/nlmixr2output.R#L98-L121

**Comment by mattfidler** [comment]
The reason is that for lognormally distributed values the `CV%` is constant.  For normally distributed items `SD` is constant.  For the others, might as well use SD.

If you did use CV for normal you would need the theta to calculate the CV%
