### ISSUE TITLE
OFV Increase following what appears to be an integration error

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#374]
I have a complex model with where I'm trying to work around likely collinearity in some of the estimates.  During estimation of some of the attempted models, I get the following message and then the OFV increases dramatically (in the current case, it goes from ~6000 to ~130000).

```
unhandled error message: EE:lsoda -- at t = 0.15 and step size _rxC(h) = 1.859e-14, the
 corrector convergence failed repeatedly or
 with fabs(_rxC(h)) = hmin
 @(lsoda.c:889
```

Would it make sense to recalculate the Gill Difference (which I think is similar to recalculating the Hessian) when this error occurs to see if it can be recovered rather than causing the parameter increase?

**Comment by mattfidler** [comment]
Gill difference calculates the optimal step size for numeric differences.  While it is definitely more expensive I doubt it would give any substantial gains for objective function surfaces that change abruptly.

In fact, it may give a numeric difference size that does not quite reflect what is going on throughout the optimization, which could also bias the results.

If you are having a hard time, you could try a different optimizer instead like `foceiControl(outerOpt="bobyqa}` or `foceiControl(outerOpt="lbfgsb3c")`

**Comment by billdenney** [comment]
Thanks.  My best model was definitely not the one that had the issue, so it didn't warrant a lot more work (the answer of "it's unstable" was sufficient for the question at hand).  I'll try bobyqa, and overall, that was the answer that I was looking for, I think.
