### ISSUE TITLE
Add `as.rxUi` method for model fits (nlmixr2FitCore objects)

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#377]
Related to nlmixr2/nlmixr2targets#9

It seems like there should be a way to coerce nlmixr2est objects into their rxUi objects to allow some programming options around models.

I think that it would be preferable to make something like:

```
as.rxUi.nlmixr2FitCore <- function(x) {
  x$ui
}
```

Another option would be to modify the `rxode2::as.rxUi.default` function to work the same as `rxode2::as.rxUi.rxode2`.

**Comment by mattfidler** [comment]
This is fine.  

`assertRxUi` should also have something for this

**Comment by billdenney** [comment]
If there is an `as.rxUi` function, `assertRxUi` will automatically work since it calls `as.rxUi`.
