### ISSUE TITLE
Feature request: Calculate shrinkage even when the covariance step fails

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#428]
When the covariance step fails, the shrinkage is not calculated.  The column is blank.

I don't think that the shrinkage should depend on the covariance step, so it would help if it were calculated to show all known about the model.

**Comment by mattfidler** [comment]
Did you look at fit$shrink or are you saying it isn't in the table of parameter estimates.

**Comment by billdenney** [comment]
It isn't in the table of parameter estimates.

**Comment by mattfidler** [comment]
I'm sorry @billdenney I will need a reproducible expression.  I just looked at this when looking at the `literalFix` branch.  For me, even when there was not a successful covariance step, the shrinkage was added to the fit.

Once you have a reproducible expression, feel free to open this issue again.
