### ISSUE TITLE
`est = "posthoc"` provides the same values for PRED and IPRED

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#436]
The same model I've been working on for the past few days has an issue where when I use `est = "posthoc"`, I get the same values for the PRED and IPRED columns.  Is there any reason that this should be happening?

**Comment by mattfidler** [comment]
If the EBE for all subjects is zero

**Comment by billdenney** [comment]
The EBE aren't all zero.

For the moment, my work-around is to remove the iiv from the `ini()` block of the model, `left_join(data, ranef(model))`, and then use `est = "rxSolve"`.

**Comment by mattfidler** [comment]
That's an OK workaround, though it shouldn't be the goto solution.

**Comment by mattfidler** [comment]
Without a reproducible example, I cannot fix this :face_with_head_bandage:   I will close this for now.  Once you get a reproducible example I will look at this a bit more.
