### ISSUE TITLE
Feature request: on integration error, try a different set of parameters

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#440]
I think that on integration error, nlmixr2est tries things like a smaller hmin and max step size or similar integrator changes.

Is it possible to try a different set of parameters instead (or in addition)?

**Comment by mattfidler** [comment]
It only tries different atol and rtol.  While it could try different parameters that would not really work with the optimization algorithms.

**Comment by mattfidler** [comment]
Because it would break fundamental optimization I will close this for now.
