### ISSUE TITLE
`nlmixr2(model)` in a model with its environment runs out of memory, removing the environment from the model runs immediately

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#448]
I can't readily make a reprex from this because it has something to do with the entire environment.

When I run a model that is only a function (with its attached environment) like this:

```
.ui <- nlmixr2est::nlmixr2(model)
```

it runs out of memory.

When I run it setting the environment to `emptyenv()` like this, I still run out of memory:

```
.ui <- nlmixr2est::nlmixr2(model, envir = emptyenv())
```

When I manually drop the environment like this, it's fine:

```
modelNoEnv <- model
environment(modelNoEnv) <- emptyenv()
.ui <- nlmixr2est::nlmixr2(modelNoEnv)
```

Any ideas what could be causing that or how to trace it?

The model itself is a pretty simple 3-compartment model.  When I try to make a reprex since the environment is different than the full environment that I'm working in, I can't reproduce it.

**Comment by mattfidler** [comment]
Unfortunately, I have no idea.

You could try to see if it is `nlmixr2` itself which could narrow down the possibilities.  

In the same place that is causing the issue do:

.ui <- rxode2::rxode2(model)

This could fix it?

**Comment by mattfidler** [comment]
I am assuming you could not find a reproducible example. I will close this for now.
