### ISSUE TITLE
Documentation request: List the choices for the `est` argument to `nlmixr2()`

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#94]
The available estimation methods are not clear from the documentation of `nlmixr2()`.  It would help to either give them explicitly, or perhaps better yet both do that and point the user to documentation of how to use the various estimation methods (possibly an estimation method vignette or manual chapter).

**Comment by mattfidler** [comment]
Since this can be modified by external packages, perhaps only the methods provided by `nlmixr2est`

**Comment by billdenney** [comment]
Since it's modifiable, then I think it would start with those provided by nlmixr2est.  And, also it would help if there were a function to give a list of all available est options.  (Which may be `methods("nlmixr2Est")`.)
